// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"we_book/internal/repository"
	article2 "we_book/internal/repository/article"
	"we_book/internal/repository/cache"
	"we_book/internal/repository/dao"
	"we_book/internal/repository/dao/article"
	"we_book/internal/service"
	"we_book/internal/web"
	"we_book/internal/web/jwt"
	"we_book/ioc"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := InitRedis()
	handler := jwt.NewRedisJWTHandler(cmdable)
	v1 := InitLogger()
	v := ioc.InitMiddlewares(cmdable, handler, v1)
	db := InitDB()
	userDAO := dao.NewUserDAO(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	codeCache := cache.NewRedisCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := InitSMSService()
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, codeService, handler)
	articleDAO := article.NewGORMArticleDAO(db)
	articleRepository := article2.NewArticleRepository(articleDAO)
	articleService := service.NewArticleService(articleRepository)
	articleHandler := web.NewArticleHandler(articleService, v1)
	wechatService := InitPhoneToWechatService(v1)
	wechatHandlerConfig := NewWechatHandlerConfig()
	oAuth2WeChatHandler := web.NewOAuth2WeChatHandler(wechatService, userService, handler, wechatHandlerConfig)
	engine := ioc.InitWebServer(v, userHandler, articleHandler, oAuth2WeChatHandler)
	return engine
}

func InitArticleHandler(dao2 article.ArticleDAO) *web.ArticleHandler {
	articleRepository := article2.NewArticleRepository(dao2)
	articleService := service.NewArticleService(articleRepository)
	v1 := InitLogger()
	articleHandler := web.NewArticleHandler(articleService, v1)
	return articleHandler
}

// wire.go:

var thirdProviderSet = wire.NewSet(InitRedis, InitLogger, InitDB, InitMongoDB)

var userSvcProviderSet = wire.NewSet(dao.NewUserDAO, cache.NewUserCache, repository.NewUserRepository, service.NewUserService, web.NewUserHandler)

var codeSvcProviderSet = wire.NewSet(cache.NewRedisCodeCache, repository.NewCodeRepository, service.NewCodeService)

var articleSvcProviderSet = wire.NewSet(article.NewGORMArticleDAO, article2.NewArticleRepository, service.NewArticleService, web.NewArticleHandler)
