// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"github.com/google/wire"
	"we_book/interactive/repository"
	"we_book/interactive/repository/cache"
	"we_book/interactive/repository/dao"
	"we_book/interactive/service"
)

// Injectors from wire.go:

func NewInteractiveService() service.InteractiveService {
	cmdable := InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	db := InitDB()
	interactiveDAO := dao.NewGORMInteractiveDAO(db)
	v1 := InitLog()
	interactiveRepository := repository.NewCacheInteractiveRepository(interactiveCache, interactiveDAO, v1)
	interactiveService := service.NewInteractiveService(interactiveRepository, v1)
	return interactiveService
}

// wire.go:

var thirdProvider = wire.NewSet(InitDB, InitRedis, InitLog)

var interactiveProvider = wire.NewSet(service.NewInteractiveService, repository.NewCacheInteractiveRepository, dao.NewGORMInteractiveDAO, cache.NewRedisInteractiveCache)
